version: "3"
services:
    minecraft:
        container_name: minecraft
        image: itzg/minecraft-server:1.7.0
        environment:
            EULA: "TRUE"
            TZ: Australia/Melbourne
            TYPE: PAPER
            VERSION: 1.16.4
            PASSWORD: <your_password>
        ports:
            - 25565:25565
        volumes:
            - ./minecraft:/data
# docker exec -i minecraft rcon-cli
