name: sp
version: 1.0.0-alpha.3.4
main: dev.applegamer22.sp.Main
api-version: "1.16"
load: STARTUP
commands:
    password:
        description: command for password input
        usage: /password [password]
        permission: sp.password
        permission-message: You don't have <permission>
permissions:
    sp.password:
        default: true