name: build-jar
on:
  release:
    types: [published]
jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF##*/}
      - run: ls build/libs/
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{github.repository_owner}}/sp/releases/${{steps.get_version.outputs.VERSION}}/assets?name=sp-${{steps.get_version.outputs.VERSION}}.jar
          asset_name: sp-${{ steps.get_version.outputs.VERSION }}.jar
          asset_path: ./build/libs/sp-${{steps.get_version.outputs.VERSION}}.jar
          asset_content_type: application/java-archive